name: amd64-image-build

on:
  push:
    branches: [ "amd64-image" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - 'scripts/packer/build-arm64-rpi.sh'
      - 'scripts/packer/joininbox-arm64-rpi.pkr.hcl'
  pull_request:
    branches: [ "amd64-image" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - 'scripts/packer/build-arm64-rpi.sh'
      - 'scripts/packer/joininbox-arm64-rpi.pkr.hcl'
  workflow_dispatch:

jobs:
  amd64-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set values
        run: |
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV

      - name: Hello Joininbox
        run: echo "Building the joininbox-amd64-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }} at "

      - name: Run the build script
        run: |
          cd scripts/packer/amd64
          bash amd64.sh

      - name: Upload the image
        uses: actions/upload-artifact@v3
        with:
          name: joininbox-amd64-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}
          path: ${{ github.workspace }}/*.tar.gz*
