name: arm64-rpi-image-build

on:
  push:
    branches: [ "packer" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
  pull_request:
    branches: [ "packer" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  arm64-rpi-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set values
        run: |
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV
          cat $GITHUB_ENV
          echo $GITHUB_WORKSPACE
          pwd

      - name: Hello Joininbox
        run: echo "Building the joininbox-arm64-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}"

      - name: Run the build script
        run: |
          chmod +x ./.github/scripts/build-arm64-rpi.sh
          ./.github/scripts/build-arm64-rpi.sh
        shell: bash

      - name: Upload the image
        uses: actions/upload-artifact@v3
        with:
          name: joininbox-arm64-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}
          path: ${{ github.workspace }}/packer-builder-arm/*.tar.gz*
