name: arm64-rpi-image-build

on:
  push:
    branches: [ "packer" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - 'scripts/packer/build-amd64.sh'
      - 'scripts/packer/joininbox-amd64.pkr.hcl'
      - 'scripts/packer/http'
  pull_request:
    branches: [ "packer" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
      - 'scripts/packer/build-amd64.sh'
      - 'scripts/packer/joininbox-amd64.pkr.hcl'
      - 'scripts/packer/http'
  workflow_dispatch:

jobs:
  arm64-rpi-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set values
        run: |
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV

      - name: Hello Joininbox
        run: echo "Building the joininbox-arm64-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}"

      - name: Run the build script
        run: |
          cd scripts/packer
          bash build-arm64-rpi.sh

      - name: Upload the image
        uses: actions/upload-artifact@v3
        with:
          name: joininbox-arm64-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}
          path: ${{ github.workspace }}/scripts/packer/packer-builder-arm/*.tar.gz*
