name: joininbox-arm64-image-build

on:
  push:
    branches: [ "packer" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
  pull_request:
    branches: [ "packer" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  arm64-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Hello Joininbox
        run: VERSION=$(git describe --tags)
        run: DATE=$(date +"%Y-%m-%d"))
        run: echo Building the JoininBox Image ${VERSION}!

      # Add permissions to file
      - name: Add executable
        run: chmod +x "${GITHUB_WORKSPACE}/.github/scripts/build.sh"

      # Run the build script
      - name: Build script
        run: ./.github/scripts/build.sh
        shell: bash

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: joininbox-arm64-image-${VERSION}-${DATE}
          path: ${{ github.workspace }}/packer-builder-arm/joininbox-arm64.img
